### ISSUE TITLE
Restrict `bevy` dependency to something smaller, ie `bevy_core`

### ISSUE THREAD

**Issue by mrchantey** [iiYese/aery#18]
At a glance `aery` only uses the `bevy_ecs` and `bevy_derive` crates, would you be open to restricting the bevy dependency to these? It could reduce compile times and make `aery` more feasable for non-graphics applications.

**Comment by iiYese** [comment]
Can do for 0.5

**Comment by iiYese** [comment]
I'll do it for the next release. I'm having hardware issues rn so just getting 0.5 out with 0.12 support is more urgent.

**Comment by iiYese** [comment]
Added in #20
